tags:
- Added
- Changed
- Deprecated
- Removed
- Fixed
- Security
files:
- identifier: changelog
  path: ./CHANGELOG.md
  tags:
  - Added
  - Changed
  - Deprecated
  - Removed
  - Fixed
  - Security
  