name: Release

on:
  push:
    tags:
      - v*

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
  linux:
    runs-on: ubuntu-latest
    needs: create_release
    strategy: 
      matrix:
        image:
          # 5.2 Stable
          - swift:5.2-xenial
          - swift:5.2-bionic
          - swift:5.2-focal
          - swift:5.2-centos8
          - swift:5.2-amazonlinux2
        include:
          - image: swift:5.2-xenial
            IMAGE_IDENTIFIER: swift-5-2-xenial
          - image: swift:5.2-bionic
            IMAGE_IDENTIFIER: swift-5-2-bionic
          - image: swift:5.2-focal
            IMAGE_IDENTIFIER: swift-5-2-focal
          - image: swift:5.2-centos8
            IMAGE_IDENTIFIER: swift-5-2-centos8
          - image: swift:5.2-amazonlinux2
            IMAGE_IDENTIFIER: swift-5-2-amazonlinux2
    container: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -c release
      - name: Package
        run: tar -C .build/release -cvzf changes.tar.gz changes
      - name: Upload Build Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: changes.tar.gz
          asset_name: changes-${{ matrix.IMAGE_IDENTIFIER }}.tar.gz
          asset_content_type: application/gzip
  macOS:
    runs-on: macos-latest
    needs: create_release
    steps:
      - name: Select latest available Xcode
        uses: maxim-lobanov/setup-xcode@1.0
        with:
          xcode-version: latest
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -c release
      - name: Package
        run: tar -C .build/release -cvzf changes.tar.gz changes
      - name: Upload Build Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: changes.tar.gz
          asset_name: changes-swift-5-2-macOS.tar.gz
          asset_content_type: application/gzip


      
